<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

|__Term__|__Brief Description__|
|:--:|:--:|
|Subsetting|Selecting the value(s) within a data structure|
|Indexing|Referring to the selection of a value at the specified position within a data structure|
|Slicing|Referring to the selection of values at the specified range of positions within a data structure|
|Masking|Only applicable for Numpy arrays, this refers t othe selection of values that satisfy the condition as set out in the mask within the Numpy array|

# Exercise 2

In [2]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

#print(np_array_2d[:, 0])
mask = (((np_array_2d[:, 0]).astype("int")) % 2 == 1)
#print(mask)
np_array_2d[mask][:,1].tolist()



['A', 'C', 'E', 'G', 'I']

# Exercise 3

In [22]:
lst = [[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

np_lst = np.array(lst)

mask1 = np_lst == 50
mask2 = np_lst < 50
mask3 = np_lst > 50
#print(mask1)
#print(mask2)
#print(mask3)
np_lst[mask1] = 0
np_lst[mask2] = -1
np_lst[mask3] = 1
print(np_lst)

# lst2 = lst.copy()

# for inner_lst in lst2:
#     for val in range(len(inner_lst)):
#         if inner_lst[val] == 50:
#             inner_lst[val] = 0
#         elif inner_lst[val] < 50:
#             inner_lst[val] = -1
#         else:
#             inner_lst[val] = 1

# print(lst2)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
